const CONSTANTS = {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_USER_BY_ID: "GET_USER_BY_ID",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER_BY_ID: "DELETE_USER_BY_ID",
    GET_ALL_JOBS: "GET_ALL_JOBS",
    CREATE_JOB: "CREATE_JOB",
    UPDATE_JOB: "UPDATE_JOB",
    GET_JOB_BY_ID: "GET_JOB_BY_ID",
    DELETE_JOB_BY_ID: "DELETE_JOB_BY_ID",
}

export default CONSTANTS;