const CONSTANTS = {
    GET_ALL_USERS: "GET_ALL_USERS",
    GET_USER_BY_ID: "GET_USER_BY_ID",
    CREATE_USER: "CREATE_USER",
    UPDATE_USER: "UPDATE_USER",
    DELETE_USER_BY_ID: "DELETE_USER_BY_ID"
}

export default CONSTANTS;